/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ForCustomersRouteImport } from './routes/for-customers'
import { Route as ForArtistsRouteImport } from './routes/for-artists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistHandleRouteImport } from './routes/artist.$handle'
import { Route as ArtIdRouteImport } from './routes/art.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCustomersRoute = ForCustomersRouteImport.update({
  id: '/for-customers',
  path: '/for-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForArtistsRoute = ForArtistsRouteImport.update({
  id: '/for-artists',
  path: '/for-artists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistHandleRoute = ArtistHandleRouteImport.update({
  id: '/artist/$handle',
  path: '/artist/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtIdRoute = ArtIdRouteImport.update({
  id: '/art/$id',
  path: '/art/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-customers': typeof ForCustomersRoute
  '/signup': typeof SignupRoute
  '/art/$id': typeof ArtIdRoute
  '/artist/$handle': typeof ArtistHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-customers': typeof ForCustomersRoute
  '/signup': typeof SignupRoute
  '/art/$id': typeof ArtIdRoute
  '/artist/$handle': typeof ArtistHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-artists': typeof ForArtistsRoute
  '/for-customers': typeof ForCustomersRoute
  '/signup': typeof SignupRoute
  '/art/$id': typeof ArtIdRoute
  '/artist/$handle': typeof ArtistHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-artists'
    | '/for-customers'
    | '/signup'
    | '/art/$id'
    | '/artist/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-artists'
    | '/for-customers'
    | '/signup'
    | '/art/$id'
    | '/artist/$handle'
  id:
    | '__root__'
    | '/'
    | '/for-artists'
    | '/for-customers'
    | '/signup'
    | '/art/$id'
    | '/artist/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForArtistsRoute: typeof ForArtistsRoute
  ForCustomersRoute: typeof ForCustomersRoute
  SignupRoute: typeof SignupRoute
  ArtIdRoute: typeof ArtIdRoute
  ArtistHandleRoute: typeof ArtistHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-customers': {
      id: '/for-customers'
      path: '/for-customers'
      fullPath: '/for-customers'
      preLoaderRoute: typeof ForCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-artists': {
      id: '/for-artists'
      path: '/for-artists'
      fullPath: '/for-artists'
      preLoaderRoute: typeof ForArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$handle': {
      id: '/artist/$handle'
      path: '/artist/$handle'
      fullPath: '/artist/$handle'
      preLoaderRoute: typeof ArtistHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art/$id': {
      id: '/art/$id'
      path: '/art/$id'
      fullPath: '/art/$id'
      preLoaderRoute: typeof ArtIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForArtistsRoute: ForArtistsRoute,
  ForCustomersRoute: ForCustomersRoute,
  SignupRoute: SignupRoute,
  ArtIdRoute: ArtIdRoute,
  ArtistHandleRoute: ArtistHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
